version: "3"

services:
  web:
    image: docker-go-web:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/go/src/demo
    ports:
      - "8000:8000"
    working_dir: /go/src/demo
    command: go run main.go
