version: "3"

services:
  app:
    container_name: docker-jupyter
    image: docker-jupyter:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    volumes:
      - .:/home
    working_dir: /home
