version: "3"
services:
  app:
    container_name: docker-openssl
    image: docker-openssl:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "443:443"
    domainname: localhost
    hostname: app
    volumes:
      - ./certs:/certs
    working_dir: /certs
    build: .

