version: "3"

services:
  app:
    container_name: docker-swift
    image: docker-swift:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/swift/src/demo
    working_dir: /swift/src/demo
    command: swift run main.swift