version: "3"

services:
  app:
    container_name: docker-go
    image: docker-go:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/go/src/demo
    working_dir: /go/src/demo
    command: go run main.go