version: "3"

services:
  app:
    container_name: docker-node
    image: docker-node:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:8080
    volumes:
      - .:/src
    working_dir: /src
    command: "node main.js"
