version: "3"

services:
  db:
    container_name: docker-postgres
    image: docker-postgres:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /tmp/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    command: postgres
    environment:
      - DB_USER=
      - DB_PASS=
      - DB_NAME=
      - DB_TEMPLATE=